### PR TITLE
add SASL login support

### PR DESCRIPTION
**Pull request by Habbie**
Tested with freenode

### CODE REVIEW

**Comment by russss** [comment]
Merged this individually, and fixed the caps issue.

**Comment by citrin** [comment]
Hi all. I have a problem with using sasl with freenode:
```
2019/02/28 20:39:22 <-- :weber.freenode.net CAP * LS :account-notify extended-join identify-msg multi-prefix sasl                                                                                                                             
2019/02/28 20:39:22 --> CAP REQ :account-notify
2019/02/28 20:39:22 --> CAP REQ :sasl                                                                                                                                                                                                         
2019/02/28 20:39:22 <-- :weber.freenode.net CAP * ACK :account-notify                                                                                                                                                                         
2019/02/28 20:39:22 <-- :weber.freenode.net CAP * ACK :sasl                                                                                                                                                                                   
2019-02-28 20:39:30 CRITICAL main main.go:69 Error connecting to IRC server: SASL setup timed out. This shouldn't happen.
```
Any suggestions how to debug this?

**Comment by Habbie** [comment]
@citrin what git revision?

**Comment by citrin** [comment]
Latest: I've just run `go get -u github.com/irccloud/irccat` before build.

**Comment by Habbie** [comment]
Can you show a (redacted where necessary) config?

**Comment by citrin** [comment]
irccat.toml:
```
[tcp]
listen = "127.0.0.1:10179"

[http]
listen = "127.0.0.1:8045"
tls = false

[irc]
server = "weber.freenode.net:6697"
tls = true
tls_skip_verify = false
nick = "citrin"
sasl_login = "citrin"
sasl_pass = "some_secret"
realname = "Anton"
```

**Comment by citrin** [comment]
I've started to debug and as I can see server reply `:weber.freenode.net CAP * ACK :sasl ` contains space after sasl. We need to strip this space somewhere before calling ACK callbacks.

**Comment by Habbie** [comment]
I have reproduced your failure here.

**Comment by Habbie** [comment]
The space does not appear to be the issue.

**Comment by Habbie** [comment]
> The space does not appear to be the issue.

I was wrong. You were right about the space.

This crude patch to go-ircevent makes it work for me. This is not the patch that should be merged!
```
diff --git a/irc_sasl.go b/irc_sasl.go
index 3346a46..7446788 100644
--- a/irc_sasl.go
+++ b/irc_sasl.go
@@ -20,7 +20,7 @@ func (irc *Connection) setupSASLCallbacks(result chan<- *SASLResult) {
 					result <- &SASLResult{true, errors.New("no SASL capability " + e.Arguments[2])}
 				}
 			}
-			if e.Arguments[1] == "ACK" && e.Arguments[2] == "sasl" {
+			if e.Arguments[1] == "ACK" && strings.TrimSpace(e.Arguments[2]) == "sasl" {
 				if irc.SASLMech != "PLAIN" {
 					result <- &SASLResult{true, errors.New("only PLAIN is supported")}
 				}
```

I would, however, recommend that this patch be merged:
```
diff --git a/irc.go b/irc.go
index 45701d3..43d2192 100644
--- a/irc.go
+++ b/irc.go
@@ -71,7 +71,7 @@ func (irc *Connection) readLoop() {
 			}
 
 			if irc.Debug {
-				irc.Log.Printf("<-- %s\n", strings.TrimSpace(msg))
+				irc.Log.Printf("<-- %q\n", msg)
 			}
 
 			irc.lastMessageMutex.Lock()
@@ -167,7 +167,7 @@ func (irc *Connection) writeLoop() {
 			}
 
 			if irc.Debug {
-				irc.Log.Printf("--> %s\n", strings.TrimSpace(b))
+				irc.Log.Printf("--> %q\n", b)
 			}
 
 			// Set a write deadline based on the time out
```

I might PR some of this tomorrow.

**Comment by citrin** [comment]
With this change in `irccloud/go-ircevent` I can connect to the server:
```
--- a/irc.go
+++ b/irc.go
@@ -102,6 +102,7 @@ func unescapeTagValue(value string) string {
 func parseToEvent(msg string) (*Event, error) {
        msg = strings.TrimSuffix(msg, "\n") //Remove \r\n
        msg = strings.TrimSuffix(msg, "\r")
+       msg = strings.TrimSuffix(msg, " ")
        event := &Event{Raw: msg}
        if len(msg) < 5 {
                return nil, errors.New("Malformed msg from server")
```

**Comment by citrin** [comment]
>  			if irc.Debug {
> -				irc.Log.Printf("<-- %s\n", strings.TrimSpace(msg))
> +				irc.Log.Printf("<-- %q\n", msg)

This makes debug log less readable - at least we need to strip "\r\n" before logging.

**Comment by Habbie** [comment]
> This makes debug log less readable - at least we need to strip "\r\n" before logging.

I disagree - the first bug I fixed in irccat was bare `\n` being sent without `\r`

**Comment by citrin** [comment]
Yes, make it sense to log line endings in debug mode (I've forgot that with %q they will be escaped before printing).

**Comment by Habbie** [comment]
> (I've forgot that with %q they will be escaped before printing)

Ah yes, looks like this, indeed:
```
2019/02/28 22:48:51 <-- ":weber.freenode.net CAP * ACK :sasl \r\n"
```

**Comment by citrin** [comment]
It looks like a server bug. But other IRC clients ignore trailing spaces and it will be good if irccat will also ignore then. I would suggest this patch, but I'm not familiar with the code:
```
--- a/irc.go
+++ b/irc.go
@@ -102,6 +102,7 @@ func unescapeTagValue(value string) string {
 func parseToEvent(msg string) (*Event, error) {
 	msg = strings.TrimSuffix(msg, "\n") //Remove \r\n
 	msg = strings.TrimSuffix(msg, "\r")
+	msg = strings.TrimRight(msg, " ") // workaround; some servers add trailing spaces
 	event := &Event{Raw: msg}
 	if len(msg) < 5 {
 		return nil, errors.New("Malformed msg from server")
```
I will make a PR to irccloud/go-ircevent.

**Comment by russss** [comment]
This should be fixed in version 0.4.1.

**Pull request closed without merging**
